<a href="https://colab.research.google.com/github/KhanIsrakAhmed/Artificial-Intelligence-Laboratory/blob/main/AI_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Class 1**

Console Output

In [ ]:
print('Hello World')


Hello World


In [ ]:
print("Hello")
print("World")

Hello
World


In [ ]:
a = 10
b = 2.5
c = "hello"

print(a)
print(b, c)

10
2.5 hello


In [ ]:
# print without new line

print("Hello", end='>')
print("World")

print("Hello", end='')
print("World")

print("Hello", end=' ')
print("World")

Hello>World
HelloWorld
Hello World


In [ ]:
# Formatting the string
a = 15

# "The value of a is 15"
print("The value of a is", a)

# "The value of a=15"
print("The value of a={a}")
print(f"The value of a={a}")

The value of a is 15
The value of a={a}
The value of a=15


Console Input

In [ ]:
x = input()
print(x)

x = input("Enter a value:")
print(x)



10
10
Enter a value:15
15


In [ ]:
x = input()
y = input()

print(x+y)

10
20
1020


In [ ]:
x = int(input())
y = int(input())

print(x+y)

10
20
30


In [ ]:
name = input("Enter your name:")
age = int(input("Enter your age:"))
height = float(input("Enter your height in m:"))
print("Name:", name, "Age:", age, "Height:", height)

Enter your name:Mr. D
Enter your age:50
Enter your height in m:1.72
Name: Mr. D Age: 50 Height: 1.72


Operators

In [ ]:
i = 5

# i++, i--
i = i + 1
i += 1



In [ ]:
x = 2
p = 5

x ** p

32

Make a ft-in to m conversion calculator

In [ ]:
print("Feet and Inches to Meters Conversion Calculator")
print("----------------------------------------------")
x = int(input())
y = int(input())

z = (x + (y/12))/3.281

print(z)


Condition

In [ ]:
x = 5

# if(condition){
# }

if x%2==0:
  print("even")
else:
  print('odd')
print("outside if-else")

odd
outside if-else


In [ ]:
x = -7

if x>0:
  print('positive')
elif x==0:
  print('zero')
else:
  print('negative')



negative


In [ ]:
x = 15

if 10<x and x<20:
  print(f'{x} is between 10 and 20')

if 10<x<20:
  print(f'{x} is between 10 and 20')


if x<10 or x>20:
  print(f"{x} is not between 10 and 20")


15 is between 10 and 20


In [ ]:
# take an integer and check whether that is a leap year or not

x = int(input())

if x%4 == 0:
  if x%100 != 0:
    print("Leapyear")
else:
  print("Doesn't leapyear")

Looping

In [ ]:
i=0
# while(condition){
# }

while i<5:
  print('hello')
  i += 1

hello
hello
hello
hello
hello


In [ ]:
# for(int i=0; i<5; ++i){
# }

for i in range(5):
  print(i)

# for(int i=4; i<10; ++i)
for i in range(4, 10):
  print(i, end=' ')
print()

# for(int i=0; i<20; i+=2)
for i in range(0, 20, 2):
  print(i, end=' ')
print()

# for(int i=20; i>12; --i)
for i in range(20, 12, -1):
  print(i, end=' ')
print()

0
1
2
3
4
4 5 6 7 8 9 
0 2 4 6 8 10 12 14 16 18 
20 19 18 17 16 15 14 13 


###Practice problems for Basic Syntax, I/O, Condition, Looping

**Multiples of 3**: Write a program that prints the numbers that are between 1 to 100 and multiples of three.

**Multiples of 3 but not multiple of 5**: Write a program that prints the numbers that are between 1 to 100 and multiples of three but not divisible 5.

**Palindrome Checker**: Write a program that checks if a given word or phrase is a palindrome. A palindrome is a word, phrase, number, or other sequence of characters that reads the same forward and backward, ignoring spaces and punctuation.

**Fibonacci Sequence**: Write a program that generates the Fibonacci sequence up to a specified number of terms. The Fibonacci sequence starts with 0 and 1, and each subsequent number is the sum of the previous two.

**Factorial Calculator**: Write a program that calculates the factorial of a given number. The factorial of a non-negative integer n is the product of all positive integers less than or equal to n.

**Prime Number Checker**: Write a program that checks if a given number is prime. A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.

In [ ]:
'''
n=3
*
**
***

n=4
*
**
***
****
'''


In [ ]:
'''
n = 5
*********
*******
*****
***
*

n = 3
*****
***
*
'''


In [ ]:
'''
n=3
  *
 **
***

n=5
    *
   **
  ***
 ****
*****
'''


In [ ]:
for i in range(1, 100):
  if i%3==0:
    print(i, end=' ')

print()
for i in range(3, 100, 3):
  print(i, end=' ')

In [ ]:
for i in range(1, 100):
  if i%3==0 and i%5!=0:
    print(i, end=' ')


**Class 2**

List

In [ ]:
list1 = [10, 20, -6 , 90, 17]

print(len(list1))
list1[2]

5


-6

In [ ]:
list1 = [10, 20, -6 , 90, 17]

for i in range(len(list1)):
  print(list1[i], end=' ')

print()
print(list1)

10 20 -6 90 17 
[10, 20, -6, 90, 17]


In [ ]:
list1 = [10, 20, -5, 9, 0]

list1.append(85)
print(list1)

list1.insert(2, 100)
print(list1)

list1.remove(9)
print(list1)

[10, 20, -5, 9, 0, 85]
[10, 20, 100, -5, 9, 0, 85]
[10, 20, 100, -5, 0, 85]


In [ ]:
list2 = [10, "world", 120, 20.5, "hello"]

In [ ]:
list1 = [10, 20, 100, -5, 9, 0, 85]

sublist1 = list1[2:6] # slicing
print(sublist1)

[100, -5, 9, 0]


In [ ]:
list1 = [10, 20, 100, -5, 9, 0, 85]
print(list1[2])
print(list1[-2])

100
0


In [ ]:
list1 = [10, 20, 100, -5, 9, 0, 85]

list1.sort()
print(list1)

[-5, 0, 9, 10, 20, 85, 100]


In [ ]:
list1 = [10, 20, 100, -5, 9, 0, 85]

list1.sort(reverse=True)
print(list1)

[100, 85, 20, 10, 9, 0, -5]


In [ ]:
list1 = [10, 11, -5]
list2 = [5, -6, 1]

list1 + list2

[10, 11, -5, 5, -6, 1]

In [ ]:
list1 = [10, 11, -5]
list2 = [5, -6, 1]

list1.extend(list2)
list1

[10, 11, -5, 5, -6, 1]

Function

In [ ]:
# int functionname(int x, float y){
#     return 0;
# }

def functionname(x, y):
  return 0

In [ ]:
def printHello():
  print('hello')

printHello()

hello


In [ ]:
def squarefn(x):
  return x*x

y = squarefn(10)
print(y)

100


In [ ]:
def isPrime(n):
  for i in range(2, n):
    if n%i==0:
      return False
  return True

isPrime(73)
isPrime(86)

True

In [ ]:
# Default Arguments
def printInfo(name, age='N/A', cgpa='N/A'):
  print(f'Name: {name}, Age: {age}, CGPA: {cgpa}')

printInfo("Mr.Z", 35, 3.87)
printInfo("Mr.Z", 35)
printInfo("Mr.Z")
# printInfo()



Name: Mr.Z, Age: 35, CGPA: 3.87
Name: Mr.Z, Age: 35, CGPA: N/A
Name: Mr.Z, Age: N/A, CGPA: N/A


In [ ]:
# Keyword/Named Arguments
def printInfo(name, age, cgpa='N/A'):
  print(f'Name: {name}, Age: {age}, CGPA: {cgpa}')

printInfo(age=35, cgpa=3.87, name="Mr.Z")
printInfo(age=35, name="Mr.Z")
# printInfo()



Name: Mr.Z, Age: 35, CGPA: 3.87
Name: Mr.Z, Age: 35, CGPA: N/A


Tuple

In [ ]:
t1 = (1,2,3)

print(t1)

x, y, z = t1

print(x, y, z)

t1[2]

(1, 2, 3)
1 2 3


3

Dictionary

In [ ]:
name_dict = {
    "joseph": 3.85,
    "alex": 3.2,
    "john": 3.9,
    "jane": 3.5
}

print(name_dict["joseph"])
print(name_dict["john"])

if "jane" in name_dict:
  print("jane exists")
if "doe" in name_dict:
  print("doe exists")

name_dict["doe"] = 3.65
print(name_dict)

if "jane" in name_dict:
  print("jane exists")
if "doe" in name_dict:
  print("doe exists")

name_dict.pop("jane")
print(name_dict)

if "jane" in name_dict:
  print("jane exists")
if "doe" in name_dict:
  print("doe exists")


3.85
3.9
jane exists
{'joseph': 3.85, 'alex': 3.2, 'john': 3.9, 'jane': 3.5, 'doe': 3.65}
jane exists
doe exists
{'joseph': 3.85, 'alex': 3.2, 'john': 3.9, 'doe': 3.65}
doe exists


In [ ]:
name_dict = {
    "joseph": 3.85,
    "alex": 3.2,
    "john": 3.9,
    "jane": 3.5
}

for k in name_dict.keys():
  print(k, '->', name_dict[k])

for k,v in name_dict.items():
  print(k, '->', v)

joseph -> 3.85
alex -> 3.2
john -> 3.9
jane -> 3.5
joseph -> 3.85
alex -> 3.2
john -> 3.9
jane -> 3.5


In [ ]:
list_int = [3, 4, 3, 0, 1, 3, 3, 4, 2, 7, 8, 7]

count_dict = {}


for v in list_int:
  if v in count_dict:
    count_dict[v] += 1
  else:
    count_dict[v] = 1

print(count_dict)

{3: 4, 4: 2, 0: 1, 1: 1, 2: 1, 7: 2, 8: 1}


In [ ]:
ar = [10, -5, 455, 299, -50, 365, 500, 75]
print(max(ar))
print(min(ar))


500
-50


public class Student {
    String first_name;
    String last_name;
    double cgpa;
    int age;

    Student(String fname, String lname, double cgpa, int age){
        first_name = fname;
        last_name = lname;
        this.cgpa = cgpa;
        this.age = age;
    }

    void printFullname(){
        println(first_name + last_name)
        println(this.first_name + this.last_name)
    }
}

obj = new Student("A", "B", 3.8, 22)

In [ ]:
class Student:
  def __init__(self, fname, lname, cgpa, age):
    self.first_name = fname
    self.last_name = lname
    self.cgpa = cgpa
    self.age = age

  def printFullName(self):
    print(self.first_name + ' ' + self.last_name)

obj = Student("Mr.", "Z", 3.88, 45)
obj.printFullName()

obj.first_name = "Ms."
obj.printFullName()

Mr. Z
Ms. Z


###NumPy

In [ ]:
import numpy as np

a = np.array([5, -2, 15, 90])
a

array([ 5, -2, 15, 90])

In [ ]:
a = np.array([21,2,-35,-4,5,66,-72,8,9])

b = np.array([[1, 4],
              [6, 2],
              [3, 5]])

print(a.shape)
print(b.shape)
r,c = b.shape
print(r,c)

(9,)
(3, 2)
3 2


In [ ]:
a = np.array([21,2,-35,-4,5,66,-72,8,9])

b = np.array([[1, 4],
              [6, 2],
              [3, 5]])

print(a.max())
print(b.max())

print("Column Wise", b.max(axis = 0))
print("Row Wise", b.max(axis = 1))

print("Column Wise", b.min(axis = 0))
print("Row Wise", b.min(axis = 1))

print("Column Wise", b.sum(axis = 0))
print("Row Wise", b.sum(axis = 1))

print("Column Wise", b.mean(axis = 0))
print("Row Wise", b.mean(axis = 1))

66
6
Column Wise [6 5]
Row Wise [4 6 5]
Column Wise [1 2]
Row Wise [1 2 3]
Column Wise [10 11]
Row Wise [5 8 8]
Column Wise [3.33333333 3.66666667]
Row Wise [2.5 4.  4. ]


In [ ]:
a = np.array([[1,5,3],
              [4,2,6]])

b = np.array([[9,2,1],
              [6,1,0]])


print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[10  7  4]
 [10  3  6]]
[[-8  3  2]
 [-2  1  6]]
[[ 9 10  3]
 [24  2  0]]
[[0.11111111 2.5        3.        ]
 [0.66666667 2.                inf]]


<ipython-input-53-cb2035a12d3c>:11: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[1,2,3],
              [4,5,6]])

print(b.T)
print(b.T.shape)

c = np.matmul(a, b.T)
print(c)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[14 32]
 [32 77]]


In [ ]:
a = np.array([21,2,-35,-4,5,66,-72,8,9])

b = np.array([[1, 4],
              [6, 2],
              [3, 5]])

print(a.argmax())
print(b.argmax())

print("Column Wise", b.argmax(axis = 0))
print("Row Wise", b.argmax(axis = 1))


5
2
Column Wise [1 2]
Row Wise [1 0 1]


In [ ]:
# Broadcasting

a = np.array(
    [[1,2],
     [3,4]]
)
b = np.array(
    [2,3]
)

a+b

array([[3, 5],
       [5, 7]])

In [ ]:
b = np.array([[1, 4, 9, 10],
              [6, 2, -1, -8],
              [3, -5, 2, 15],
              [31, 5, 12, -5]])


print(b[1][2])
print(b[0:2]) # first two rows
print(b[0:2, :]) # first two rows
print(b[:, 1:3]) # middle two columns
print(b[:, -1]) # last column
print(b[:, -2:]) # last two columns
print(b[:, 2:]) # after first two columns
print(b[1:3, 1:4]) # middle 4 elements


-1
[[ 1  4  9 10]
 [ 6  2 -1 -8]]
[[ 1  4  9 10]
 [ 6  2 -1 -8]]
[[ 4  9]
 [ 2 -1]
 [-5  2]
 [ 5 12]]
[10 -8 15 -5]


In [ ]:
a = np.array([3, -5, 2, -8, 9, 0, 7])

print(a.shape)

a.reshape((1, 7))
a.reshape((7, 1))

(7,)


array([[ 3],
       [-5],
       [ 2],
       [-8],
       [ 9],
       [ 0],
       [ 7]])

In [ ]:
a = np.array([3, -5, 2, -8])

print(a.shape)

a.reshape((2, 2))
a.reshape((2, 2)).T

(4,)


array([[ 3, -5],
       [ 2, -8]])

Filtering

In [ ]:
a = np.array([3, -5, 2, -8, 9, 0, 7])

print("a", a)

print("a[[True, False, False, True, True, False, True]]", a[[True, False, False, True, True, False, True]])

print("a>5", a>5)

print("a[a>5]", a[a>5])
print("a[a<2]", a[a<2])


a [ 3 -5  2 -8  9  0  7]
a[[True, False, False, True, True, False, True]] [ 3 -8  9  7]
a>5 [False False False False  True False  True]
a[a>5] [9 7]
a[a<2] [-5 -8  0]
